"""init schema

Revision ID: 9f2aeb7556db
Revises: 
Create Date: 2025-12-10 02:32:46.953197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9f2aeb7556db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_favorites_business_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_reviews_business_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_checkins_business_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_business_memberships_business_id'), table_name='business_memberships')
    op.drop_index(op.f('ix_business_memberships_user_id'), table_name='business_memberships')
    op.drop_table('business_memberships')
    op.drop_index(op.f('ix_business_vetting_id'), table_name='business_vetting')
    op.drop_index(op.f('ix_business_vetting_user_id'), table_name='business_vetting')
    op.drop_table('business_vetting')
    op.drop_index(op.f('ix_business_submissions_id'), table_name='business_submissions')
    op.drop_index(op.f('ix_business_submissions_owner_id'), table_name='business_submissions')
    op.drop_table('business_submissions')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lng', sa.FLOAT(), nullable=True),
    sa.Column('address1', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('zip', sa.VARCHAR(), nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=False),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('approved_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('hide_address', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_table('business_submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lng', sa.FLOAT(), nullable=True),
    sa.Column('address1', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('zip', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('review_notes', sa.VARCHAR(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_business_id', sa.INTEGER(), nullable=True),
    sa.Column('hide_address', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['created_business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_submissions_owner_id'), 'business_submissions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_business_submissions_id'), 'business_submissions', ['id'], unique=False)
    op.create_table('business_vetting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('submission_id', sa.INTEGER(), nullable=False),
    sa.Column('business_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('answers', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['business_submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_business_vetting_user_id'), 'business_vetting', ['user_id'], unique=False)
    op.create_index(op.f('ix_business_vetting_id'), 'business_vetting', ['id'], unique=False)
    op.create_table('business_memberships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('business_id', sa.INTEGER(), nullable=False),
    sa.Column('membership_role', sa.VARCHAR(length=7), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_id', name=op.f('uq_user_business'))
    )
    op.create_index(op.f('ix_business_memberships_user_id'), 'business_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_business_memberships_business_id'), 'business_memberships', ['business_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('business_id', sa.INTEGER(), nullable=False),
    sa.Column('visited_at', sa.DATETIME(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_index(op.f('ix_checkins_business_id'), 'checkins', ['business_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('business_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('is_flagged', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_business_id'), 'reviews', ['business_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('business_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_id', name=op.f('uq_fav_user_business'))
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_business_id'), 'favorites', ['business_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=8), nullable=False),
    sa.Column('email_verified_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    # ### end Alembic commands ###
